library routes;

export './routes.dart';
export './names.dart';
export 'package:flutter/material.dart';
export 'package:get/get.dart';
export 'package:roudy_story_box/view/frames/splash/page.dart';
export 'package:roudy_story_box/view/frames/onboarding1/page.dart';
export 'package:roudy_story_box/view/frames/onboarding2/page.dart';
export 'package:roudy_story_box/view/frames/splash/bindings.dart';
export 'package:roudy_story_box/view/frames/chatboard/page.dart';
export 'package:roudy_story_box/view/frames/home/page.dart';
export 'package:roudy_story_box/view/frames/login/page.dart';
export 'package:roudy_story_box/view/frames/profilecreation/page.dart';
export 'package:roudy_story_box/view/frames/profilemanagement/page.dart';
export 'package:roudy_story_box/view/frames/signup/page.dart';
export 'package:roudy_story_box/view/frames/welcome/page.dart';
export 'package:roudy_story_box/view/frames/onboarding1/bindings.dart';
export 'package:roudy_story_box/view/frames/home/bindings.dart';
export 'package:roudy_story_box/view/frames/chatboard/bindings.dart';

export 'package:roudy_story_box/view/frames/login/bindings.dart';
export 'package:roudy_story_box/view/frames/onboarding2/bindings.dart';
export 'package:roudy_story_box/view/frames/profilecreation/bindings.dart';
export 'package:roudy_story_box/view/frames/profilemanagement/bindings.dart';
export 'package:roudy_story_box/view/frames/signup/bindings.dart';
export 'package:roudy_story_box/view/frames/welcome/bindings.dart';
// export 'package:roudy_story_box/view/frames/onboarding1.dart';
// export 'package:my_chat_app/view/register/index.dart';
// export 'package:my_chat_app/view/connection/index.dart';
// export 'package:my_chat_app/view/auth/index.dart';
// export 'package:my_chat_app/view/user_info/index.dart';
// export 'package:my_chat_app/view/home/index.dart';
// export 'package:my_chat_app/view/messages/index.dart';